### ISSUE TITLE
confusing uninstall messaging for dotted attr_paths

### ISSUE THREAD

**Issue by billlevine** [flox/flox#1714]
**Describe the bug:**
When installing a package with a dotted path, and then try to uninstall the same, you get an error saying that it is not installed in the environment.

**Steps to reproduce:**
1. Install a dotted package like `python311Pakcages.tensorflow-bin`
2. Try to uninstall the same.

Result:
You get the error saying that the package is not installed.

Expected:
The package is uninstalled correctly.

**Screenshots/terminal output (if relevant):**
```
> flox install python311Packages.tensorflow-bin
✅ 'tensorflow-bin' installed to environment 'foo'

> flox uninstall python311Packages.tensorflow-bin
❌ ERROR: Failed to modify manifest.

couldn't uninstall 'python311Packages.tensorflow-bin', wasn't previously installed

> flox list
tensorflow-bin: python311Packages.tensorflow-bin (python3.11-tensorflow-2.16.1)

> flox uninstall tensorflow-bin
🗑️  'tensorflow-bin' uninstalled from environment 'foo'
```

**flox Version (run `flox --version` if possible):**

v1.1.0

**Comment by ghudgins** [comment]
this was a sort of compromise at the time when we made the `id` attribute. I do agree it's sub optimal. it would be good if we could "know what you mean" and try to uninstall the right side of a dotted uninstall by ID or some other solution.

**Comment by billlevine** [comment]
Understood.  I'm thinking something like...

- If the given term isn't found as an `install-id`, look for a `pkg-path` that matches.
- If a single descriptor is found, uninstall it.
- If no descriptors are found, error out as we do.
- If multiple descriptors are found, say "XYZ is ambiguous, please use the `install-id`, one of _foo_, _bar_,_bat".  Or we could prompt which they want to uninstall including an option for _all_.

**Comment by mkenigs** [comment]
> Understood. I'm thinking something like...
> 
>     * If the given term isn't found as an `install-id`, look for a `pkg-path` that matches.
> 
>     * If a single descriptor is found, uninstall it.
> 
>     * If no descriptors are found, error out as we do.
> 
>     * If multiple descriptors are found, say "XYZ is ambiguous, please use the `install-id`, one of _foo_, _bar_,_bat".  Or we could prompt which they want to uninstall including an option for _all_.

+1

**Comment by ghudgins** [comment]
sounds good

**Comment by tanjadev** [comment]
I pushed a fix for this. One thing I wasn't able to reproduce is this: 

> If multiple descriptors are found, say "XYZ is ambiguous, please use the install-id, one of foo, bar,_bat".

If somebody is willing to maybe do a quick testing session together to verify that it behaves as expected and the fix coveres all the various cases, it would be mighty appreciated. @ghudgins maybe you have time?

**Comment by ghudgins** [comment]
I gave it a review. that case doesn't actually exist since we key off the `id`. just a lapse at the time I think.

**Comment by billlevine** [comment]
I think it can still happen if you have the same package installed at different versions for different systems for example?  I can try to reproduce what I was thinking.

**Comment by tanjadev** [comment]
Right, I think this should behave as @billlevine described: The current implementation behaves as follows:  

If  there are multiple packages match the provided pkg-path, we ask the user to specify the install id instead: 
![image](https://github.com/user-attachments/assets/e4ec48fd-e0af-4233-8a4d-3f60a8f1ba05)

It actually uninstalls the package by pkg path if there's a match, even if the install id is something different. In the following example we delete `nodePackages.emacs`, although the install id is `realemacsnpm`. (You can also use the install id `realemacsnpm` to uninstall)
![image](https://github.com/user-attachments/assets/25a9edb9-a2f8-4b5a-b885-1bf097ffcabf)
