### ISSUE TITLE
Cannot define bash functions in nested/layered environments

### ISSUE THREAD

**Issue by sudermanjr** [flox/flox#2181]
**Describe the bug:**
I have a default environment with a bash function in it, which works great. When I add a function to another environment, and then flox activate that one, they're both active, but the functions defined in the non-default environment don't seem to work.

**Steps to reproduce:**
1. Create a default flox env in your home
2. Add the following to the [profile] section:
```
bash = '''
  bash_specific_function() {
    echo "This logic runs using the version of bash on the local system"
  }

  alias doit='bash_specific_function'
'''
```

3. Create a separate flox env with flox init
4. Add a function to the [profile] section
```
bash = '''
  bash_specific_function2() {
    echo "This logic runs using the version of bash on the local system"
  }

  alias doit2='bash_specific_function2'
'''
```
5. Activate the new environment
6. Try to run both functions

Result:
```
home [default]
▶ doit
This logic runs using the version of bash on the local system
home [default]
▶ doit2
bash: doit2: command not found
home [default]
home [default]
✗ flox activate -d .fairwinds/fw-flox/
✅ You are now using the environment 'fw'.
To stop using this environment, type 'exit'

home [fw default]
▶ doit2
bash: doit2: command not found
```

Expected:
`doit2` exists as a function in the shell after activating the second environment

**Screenshots/terminal output (if relevant):**
(see above)

**Flox Version (run `flox --version` if possible):**
1.3.3

**`uname -a` output:**
```
Darwin thanos.local 24.0.0 Darwin Kernel Version 24.0.0: Mon Aug 12 20:49:48 PDT 2024; root:xnu-11215.1.10~2/RELEASE_ARM64_T8103 arm64 arm Darwin
```

**Comment by mkenigs** [comment]
Are you sourcing your default environment in a dotfile? If so I think we just fixed this for zsh and were about to do the same for bash.

**Comment by sudermanjr** [comment]
Yeah, this is in my .bashrc:

```
if [ -x '/usr/local/bin/flox' ];then
    eval "$(flox activate --dir ~)"
fi
```

**Comment by sudermanjr** [comment]
Just updated to 1.3.5 and it seems like this is still an issue.

**Comment by mkenigs** [comment]
Thanks for the ping, we haven't gotten around to the fix for Bash yet :/

**Comment by mkenigs** [comment]
This is most likely caused by the fact that attach-interactive.bash -> calls bash with --rcfile -> the rc file needs environment variables, but it also sources ~/.bashrc which may activate other environments, overriding the environment variables it uses

Approaches to fix:
1. Do save and restore dance with all variables (what we did in https://github.com/flox/flox/pull/2153)
2. Do save and restore dance with a single variables that points to a file or something with more variables
3. Create a unique set of RC files for every environment

1 seems too bug prone to me and we should do 2 or 3

**Comment by mkenigs** [comment]
>     3. Create a unique set of RC files for every activation dynamically as part of the activation script

A more concrete example of how we could do this for Bash in-place activations:
```
diff --git a/assets/activation-scripts/activate.d/attach-inplace.bash b/assets/activation-scripts/activate.d/attach-inplace.bash
index 609e2146..5a1b6fb5 100644
--- a/assets/activation-scripts/activate.d/attach-inplace.bash
+++ b/assets/activation-scripts/activate.d/attach-inplace.bash
@@ -15,14 +15,14 @@ expiring_pid="$$"
 # script fragment when represented on a single line.
 case "$_flox_shell" in
   *bash)
-    echo "export _FLOX_RESTORE_PATH=\"$PATH\";"
-    echo "export _FLOX_RESTORE_MANPATH=\"$MANPATH\";"
-    echo "$_flox_activations --runtime-dir \"$FLOX_RUNTIME_DIR\" attach --pid \$\$ --flox-env \"$FLOX_ENV\" --id \"$_FLOX_ACTIVATION_ID\" --remove-pid \"$expiring_pid\";"
-    echo "export _flox_activate_tracelevel=\"$_flox_activate_tracelevel\";"
-    echo "export FLOX_ENV=\"$FLOX_ENV\";"
-    echo "export _FLOX_ACTIVATION_STATE_DIR=\"$_FLOX_ACTIVATION_STATE_DIR\";"
-    echo "export _activate_d=\"$_activate_d\";"
-    echo "source '$_activate_d/bash';"
+    ACTIVATION_FILE="mktemp in $_FLOX_ACTIVATION_STATE_DIR"
+    cat > "$ACTIVATION_FILE" <<EOF
+    _FLOX_RESTORE_PATH=\"$PATH\"
+    _FLOX_RESTORE_MANPATH=\"$MANPATH\"
+    ...
+EOF
+    cat "$_activate_d/bash" >> "$ACTIVATION_FILE"
+    echo "source '$ACTIVATION_FILE'"
     ;;
   *fish)
     echo "set -gx _FLOX_RESTORE_PATH \"$PATH\";"
```

**Comment by mkenigs** [comment]
For `$_activate_d/bash` we could pass args explicitly. For certain rc files (e.g. files in ZDOTDIR) we can take the dynamic generation approach similar to that in the diff

**Comment by zmitchell** [comment]
One problem with setting the entire `PATH` via `_FLOX_RESTORE_PATH` is that it removes the default environment from `PATH` in some cases:
- Start in a shell that doesn't have the default environment active. Let's use fish for this case.
- Assume that a Bash shell on your system does activate the default environment when created.
- Run a `FLOX_SHELL=bash flox activate -- <cmd>`
- `_FLOX_RESTORE_PATH` will be set to the `PATH` of the fish shell with the environment dirs of the environment in the current directory prepended. Note that at this point the default environment is not in `PATH`.
- Source `.bashrc`, which prepends the default environment to `PATH`.
- Restore the `PATH` from `_FLOX_RESTORE_PATH`
- You've now removed the default environment from `PATH`.

**Comment by dcarley** [comment]
This should also close https://github.com/flox/flox/issues/2194 right?

**Comment by mkenigs** [comment]
Yep

**Comment by mkenigs** [comment]
Fixed by https://github.com/flox/flox/pull/2476

**Comment by sudermanjr** [comment]
Working great. Thanks y'all!
